# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.srcs/sources_1/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0.xci
# IP: The module: 'hdmi_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.gen/sources_1/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: D:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.srcs/sources_1/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0.xci
# IP: The module: 'hdmi_dlmb_v10_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.gen/sources_1/bd/hdmi/ip/hdmi_dlmb_v10_0/hdmi_dlmb_v10_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_dlmb_v10_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
