# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.srcs/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0.xci
# IP: The module: 'hdmi_v_vid_in_axi4s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.gen/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.gen/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: D:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.srcs/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0.xci
# IP: The module: 'hdmi_v_vid_in_axi4s_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.gen/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: d:/VivadoPrj/Nexys-all-Projects/NVideoHDMI-22.1u/hw/hw/hw.gen/sources_1/bd/hdmi/ip/hdmi_v_vid_in_axi4s_0_0/hdmi_v_vid_in_axi4s_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_v_vid_in_axi4s_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
