# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.srcs/sources_1/bd/parser/ip/parser_xbar_0_1/parser_xbar_0.xci
# IP: The module: 'parser_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.gen/sources_1/bd/parser/ip/parser_xbar_0_1/parser_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'parser_xbar_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.srcs/sources_1/bd/parser/ip/parser_xbar_0_1/parser_xbar_0.xci
# IP: The module: 'parser_xbar_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.gen/sources_1/bd/parser/ip/parser_xbar_0_1/parser_xbar_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'parser_xbar_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
