# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.srcs/sources_1/bd/parser/ip/parser_ilmb_bram_if_cntlr_4/parser_ilmb_bram_if_cntlr_4.xci
# IP: The module: 'parser_ilmb_bram_if_cntlr_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.gen/sources_1/bd/parser/ip/parser_ilmb_bram_if_cntlr_4/parser_ilmb_bram_if_cntlr_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'parser_ilmb_bram_if_cntlr_4'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.srcs/sources_1/bd/parser/ip/parser_ilmb_bram_if_cntlr_4/parser_ilmb_bram_if_cntlr_4.xci
# IP: The module: 'parser_ilmb_bram_if_cntlr_4' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.gen/sources_1/bd/parser/ip/parser_ilmb_bram_if_cntlr_4/parser_ilmb_bram_if_cntlr_4_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'parser_ilmb_bram_if_cntlr_4'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
