# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/Muaz/Documents/MeteorDestroyer/MeteorDestroyerSystem/MeteorDestroyerSystem.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_3/hdmi_xbar_3.xci
# IP: The module: 'hdmi_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Muaz/Documents/MeteorDestroyer/MeteorDestroyerSystem/MeteorDestroyerSystem.gen/sources_1/bd/hdmi/ip/hdmi_xbar_3/hdmi_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_xbar_3'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/Muaz/Documents/MeteorDestroyer/MeteorDestroyerSystem/MeteorDestroyerSystem.srcs/sources_1/bd/hdmi/ip/hdmi_xbar_3/hdmi_xbar_3.xci
# IP: The module: 'hdmi_xbar_3' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Muaz/Documents/MeteorDestroyer/MeteorDestroyerSystem/MeteorDestroyerSystem.gen/sources_1/bd/hdmi/ip/hdmi_xbar_3/hdmi_xbar_3_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'hdmi_xbar_3'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
