webtalk_init -webtalk_dir C:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.sim/sim_1/behav/xsim/xsim.dir/localize_tb_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Mon Mar 10 02:55:15 2025" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2018.3 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2405991" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "01c0c4f5-0e71-4270-8320-47f6cddf9609" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "0056d15ece34404081e526e2477d6e42" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "87" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor              " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3993 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "17.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "1" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.09_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "6848_KB" -context "xsim\\usage"
webtalk_transmit -clientid 449737153 -regid "" -xml C:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.sim/sim_1/behav/xsim/xsim.dir/localize_tb_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.sim/sim_1/behav/xsim/xsim.dir/localize_tb_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Muaz/Documents/MeteorDestroyer/Parser/Parser.sim/sim_1/behav/xsim/xsim.dir/localize_tb_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
